import React from 'react';

export default function Procurement() {
  return (
    <div className="view">
      <div className="ph">
        <div className="pg">Supplier &amp; Procurement Intelligence</div>
        <div className="psub">Supplier scorecards · Performance analysis · Cost comparison · Risk flags</div>
      </div>

      <div className="kg g4">
        {[
          { cls: 'sb', l: 'Open POs', v: '8', d: '▲ ₹12.4L total value', s: '4 auto-generated by AI' },
          { cls: 'sg', l: 'Best Supplier', v: 'Century', d: '▲ 96% on-time', s: 'Below market price · Full trucks' },
          { cls: 'sr', l: 'Problem Supplier', v: 'Gauri Laminates', d: '▼ 68% on-time', s: '+11% true landed cost vs market' },
          { cls: 'sa', l: 'GRN Match Rate', v: '96%', d: '▲ 3 mismatches this month', s: '₹8,400 total variance' },
        ].map(k => (
          <div key={k.l} className={`kc ${k.cls}`}>
            <div className="kt"><div className="kl">{k.l}</div></div>
            <div className="kv">{k.v}</div>
            <div className="kd wn">{k.d}</div>
            <div className="ks">{k.s}</div>
          </div>
        ))}
      </div>

      <div className="card">
        <div className="ch"><div className="ctit">Supplier Scorecards — AI Evaluation</div><span className="bdg bg">AI Ranked</span></div>
        <table className="tbl">
          <thead>
            <tr><th>Supplier</th><th>On-Time %</th><th>Avg Delay</th><th>Price vs Market</th><th>Lead Time</th><th>Freight/Sheet</th><th>GRN Match</th><th>AI Verdict</th></tr>
          </thead>
          <tbody>
            {[
              ['Century Plyboards', 96, '0.4d', '-3% below', '5-6 days', '₹8.4', '100%', 'PREFERRED', 'bg'],
              ['Greenply Industries', 88, '1.2d', '+1% above', '7 days', '₹12.6', '94%', 'GOOD', 'bb'],
              ['Gauri Laminates', 68, '3.2d', '+6% above', '10-11 days', '₹22', '82%', 'REVIEW', 'br'],
            ].map(([n, ot, d, p, l, f, m, v, sc]) => (
              <tr key={n}>
                <td style={{ fontWeight: 600 }}>{n}</td>
                <td style={{ fontFamily: 'var(--mono)', fontWeight: 700, color: ot >= 90 ? '#16a34a' : ot >= 80 ? '#d97706' : '#dc2626' }}>{ot}%</td>
                <td style={{ fontFamily: 'var(--mono)', color: parseFloat(d) > 2 ? '#dc2626' : '#4b5563' }}>{d}</td>
                <td style={{ fontFamily: 'var(--mono)', color: p.includes('-') ? '#16a34a' : '#d97706' }}>{p}</td>
                <td style={{ fontFamily: 'var(--mono)' }}>{l}</td>
                <td style={{ fontFamily: 'var(--mono)' }}>{f}</td>
                <td style={{ fontFamily: 'var(--mono)', color: parseFloat(m) >= 95 ? '#16a34a' : '#d97706' }}>{m}</td>
                <td><span className={`bdg ${sc}`}>{v}</span></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="card" style={{ marginTop: '12px' }}>
        <div className="ch"><div className="ctit">AI Procurement Alerts</div><span className="bdg ba">Action Required</span></div>
        <div className="ilist">
          {[
            ['icr', '!', 'PO-7731 (Gauri Laminates) overdue by 4 days — ₹0.49L at risk', 'Escalate immediately. Only 38% filled. Consider emergency order from Century Plyboards.', 'OVERDUE PO · HIGH RISK'],
            ['icr', '!', 'PO-7734 (Greenply) overdue by 2 days — 300 sheets pending', 'Greenply confirmed shipment delayed due to transport strike. ETA adjusted to +3 days.', 'OVERDUE PO · MEDIUM RISK'],
            ['ica', '!', 'Gauri Laminates true landed cost is +11% above market', '₹22/sheet freight vs Century\'s ₹8.4. Evaluate switching 8mm Flexi to alternate supplier.', 'COST ANALYSIS · REVIEW'],
            ['icg', '★', 'Century Plyboards: 100% GRN match rate this month', 'Consider expanding orders. They have capacity and below-market pricing.', 'PREFERRED SUPPLIER · EXPAND'],
          ].map(([ic, icon, t, d, m]) => (
            <div key={t} className="ii">
              <div className={`iic ${ic}`}>{icon}</div>
              <div><div className="iti">{t}</div><div className="ide">{d}</div><div className="imt">{m}</div></div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
